version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.0.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-dependency-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: echo "building files"
      - run: npm i
      - run: npx ionic build
      - save_cache:
          key: node-v1-dependency-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: ls -la
      - persist_to_workspace:
          root: .
          paths:
            - build
            - firebase.json
            - '.firebaserc'
  deploy:
    docker:
      - image: circleci/node:11.0.0
    steps:
      - attach_workspace:
          at: .
      - run: ls -la
      - run:
          name: deploy to firebase
          command: npx firebase-tools deploy --token "$FIREBASE_TOKEN"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
